// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.30.2
// source: common/proto/lance.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Lance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeilaoID      *string                `protobuf:"bytes,1,req,name=LeilaoID" json:"LeilaoID,omitempty"`
	UserID        *string                `protobuf:"bytes,2,req,name=UserID" json:"UserID,omitempty"`
	Value         *float32               `protobuf:"fixed32,3,req,name=Value" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lance) Reset() {
	*x = Lance{}
	mi := &file_common_proto_lance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lance) ProtoMessage() {}

func (x *Lance) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_lance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lance.ProtoReflect.Descriptor instead.
func (*Lance) Descriptor() ([]byte, []int) {
	return file_common_proto_lance_proto_rawDescGZIP(), []int{0}
}

func (x *Lance) GetLeilaoID() string {
	if x != nil && x.LeilaoID != nil {
		return *x.LeilaoID
	}
	return ""
}

func (x *Lance) GetUserID() string {
	if x != nil && x.UserID != nil {
		return *x.UserID
	}
	return ""
}

func (x *Lance) GetValue() float32 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

var File_common_proto_lance_proto protoreflect.FileDescriptor

const file_common_proto_lance_proto_rawDesc = "" +
	"\n" +
	"\x18common/proto/lance.proto\"Q\n" +
	"\x05Lance\x12\x1a\n" +
	"\bLeilaoID\x18\x01 \x02(\tR\bLeilaoID\x12\x16\n" +
	"\x06UserID\x18\x02 \x02(\tR\x06UserID\x12\x14\n" +
	"\x05Value\x18\x03 \x02(\x02R\x05Value2(\n" +
	"\fLanceService\x12\x18\n" +
	"\x06Create\x12\x06.Lance\x1a\x06.LanceB\x03Z\x01/"

var (
	file_common_proto_lance_proto_rawDescOnce sync.Once
	file_common_proto_lance_proto_rawDescData []byte
)

func file_common_proto_lance_proto_rawDescGZIP() []byte {
	file_common_proto_lance_proto_rawDescOnce.Do(func() {
		file_common_proto_lance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_lance_proto_rawDesc), len(file_common_proto_lance_proto_rawDesc)))
	})
	return file_common_proto_lance_proto_rawDescData
}

var file_common_proto_lance_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_proto_lance_proto_goTypes = []any{
	(*Lance)(nil), // 0: Lance
}
var file_common_proto_lance_proto_depIdxs = []int32{
	0, // 0: LanceService.Create:input_type -> Lance
	0, // 1: LanceService.Create:output_type -> Lance
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_proto_lance_proto_init() }
func file_common_proto_lance_proto_init() {
	if File_common_proto_lance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_lance_proto_rawDesc), len(file_common_proto_lance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_proto_lance_proto_goTypes,
		DependencyIndexes: file_common_proto_lance_proto_depIdxs,
		MessageInfos:      file_common_proto_lance_proto_msgTypes,
	}.Build()
	File_common_proto_lance_proto = out.File
	file_common_proto_lance_proto_goTypes = nil
	file_common_proto_lance_proto_depIdxs = nil
}
