// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: ms-pagamento.proto

package mspagamento_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LanceGanhador struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeilaoID      *string                `protobuf:"bytes,1,req,name=LeilaoID" json:"LeilaoID,omitempty"`
	UserID        *string                `protobuf:"bytes,2,req,name=UserID" json:"UserID,omitempty"`
	Values        *float32               `protobuf:"fixed32,3,req,name=Values" json:"Values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LanceGanhador) Reset() {
	*x = LanceGanhador{}
	mi := &file_ms_pagamento_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LanceGanhador) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LanceGanhador) ProtoMessage() {}

func (x *LanceGanhador) ProtoReflect() protoreflect.Message {
	mi := &file_ms_pagamento_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LanceGanhador.ProtoReflect.Descriptor instead.
func (*LanceGanhador) Descriptor() ([]byte, []int) {
	return file_ms_pagamento_proto_rawDescGZIP(), []int{0}
}

func (x *LanceGanhador) GetLeilaoID() string {
	if x != nil && x.LeilaoID != nil {
		return *x.LeilaoID
	}
	return ""
}

func (x *LanceGanhador) GetUserID() string {
	if x != nil && x.UserID != nil {
		return *x.UserID
	}
	return ""
}

func (x *LanceGanhador) GetValues() float32 {
	if x != nil && x.Values != nil {
		return *x.Values
	}
	return 0
}

var File_ms_pagamento_proto protoreflect.FileDescriptor

const file_ms_pagamento_proto_rawDesc = "" +
	"\n" +
	"\x12ms-pagamento.proto\x12\vmspagamento\"[\n" +
	"\rLanceGanhador\x12\x1a\n" +
	"\bLeilaoID\x18\x01 \x02(\tR\bLeilaoID\x12\x16\n" +
	"\x06UserID\x18\x02 \x02(\tR\x06UserID\x12\x16\n" +
	"\x06Values\x18\x03 \x02(\x02R\x06Values2^\n" +
	"\n" +
	"RouteGuide\x12P\n" +
	"\x14ReceiveLanceGanhador\x12\x1a.mspagamento.LanceGanhador\x1a\x1a.mspagamento.LanceGanhador\"\x00B\x13Z\x11mspagamento.proto"

var (
	file_ms_pagamento_proto_rawDescOnce sync.Once
	file_ms_pagamento_proto_rawDescData []byte
)

func file_ms_pagamento_proto_rawDescGZIP() []byte {
	file_ms_pagamento_proto_rawDescOnce.Do(func() {
		file_ms_pagamento_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ms_pagamento_proto_rawDesc), len(file_ms_pagamento_proto_rawDesc)))
	})
	return file_ms_pagamento_proto_rawDescData
}

var file_ms_pagamento_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ms_pagamento_proto_goTypes = []any{
	(*LanceGanhador)(nil), // 0: mspagamento.LanceGanhador
}
var file_ms_pagamento_proto_depIdxs = []int32{
	0, // 0: mspagamento.RouteGuide.ReceiveLanceGanhador:input_type -> mspagamento.LanceGanhador
	0, // 1: mspagamento.RouteGuide.ReceiveLanceGanhador:output_type -> mspagamento.LanceGanhador
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ms_pagamento_proto_init() }
func file_ms_pagamento_proto_init() {
	if File_ms_pagamento_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ms_pagamento_proto_rawDesc), len(file_ms_pagamento_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ms_pagamento_proto_goTypes,
		DependencyIndexes: file_ms_pagamento_proto_depIdxs,
		MessageInfos:      file_ms_pagamento_proto_msgTypes,
	}.Build()
	File_ms_pagamento_proto = out.File
	file_ms_pagamento_proto_goTypes = nil
	file_ms_pagamento_proto_depIdxs = nil
}
