// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.30.2
// source: gateway.proto

package proto_models

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GatewayService_PublicaLanceInvalido_FullMethodName   = "/GatewayService/PublicaLanceInvalido"
	GatewayService_PublicaLanceValido_FullMethodName     = "/GatewayService/PublicaLanceValido"
	GatewayService_PublicaLeilaoVencedor_FullMethodName  = "/GatewayService/PublicaLeilaoVencedor"
	GatewayService_PublicaLinkPagamento_FullMethodName   = "/GatewayService/PublicaLinkPagamento"
	GatewayService_PublicaStatusPagamento_FullMethodName = "/GatewayService/PublicaStatusPagamento"
)

// GatewayServiceClient is the client API for GatewayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GatewayServiceClient interface {
	PublicaLanceInvalido(ctx context.Context, in *GLance, opts ...grpc.CallOption) (*GStatus, error)
	PublicaLanceValido(ctx context.Context, in *GLance, opts ...grpc.CallOption) (*GStatus, error)
	PublicaLeilaoVencedor(ctx context.Context, in *GLance, opts ...grpc.CallOption) (*GStatus, error)
	PublicaLinkPagamento(ctx context.Context, in *Link, opts ...grpc.CallOption) (*GStatus, error)
	PublicaStatusPagamento(ctx context.Context, in *StatusPayment, opts ...grpc.CallOption) (*GStatus, error)
}

type gatewayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayServiceClient(cc grpc.ClientConnInterface) GatewayServiceClient {
	return &gatewayServiceClient{cc}
}

func (c *gatewayServiceClient) PublicaLanceInvalido(ctx context.Context, in *GLance, opts ...grpc.CallOption) (*GStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GStatus)
	err := c.cc.Invoke(ctx, GatewayService_PublicaLanceInvalido_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) PublicaLanceValido(ctx context.Context, in *GLance, opts ...grpc.CallOption) (*GStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GStatus)
	err := c.cc.Invoke(ctx, GatewayService_PublicaLanceValido_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) PublicaLeilaoVencedor(ctx context.Context, in *GLance, opts ...grpc.CallOption) (*GStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GStatus)
	err := c.cc.Invoke(ctx, GatewayService_PublicaLeilaoVencedor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) PublicaLinkPagamento(ctx context.Context, in *Link, opts ...grpc.CallOption) (*GStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GStatus)
	err := c.cc.Invoke(ctx, GatewayService_PublicaLinkPagamento_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) PublicaStatusPagamento(ctx context.Context, in *StatusPayment, opts ...grpc.CallOption) (*GStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GStatus)
	err := c.cc.Invoke(ctx, GatewayService_PublicaStatusPagamento_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayServiceServer is the server API for GatewayService service.
// All implementations must embed UnimplementedGatewayServiceServer
// for forward compatibility.
type GatewayServiceServer interface {
	PublicaLanceInvalido(context.Context, *GLance) (*GStatus, error)
	PublicaLanceValido(context.Context, *GLance) (*GStatus, error)
	PublicaLeilaoVencedor(context.Context, *GLance) (*GStatus, error)
	PublicaLinkPagamento(context.Context, *Link) (*GStatus, error)
	PublicaStatusPagamento(context.Context, *StatusPayment) (*GStatus, error)
	mustEmbedUnimplementedGatewayServiceServer()
}

// UnimplementedGatewayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGatewayServiceServer struct{}

func (UnimplementedGatewayServiceServer) PublicaLanceInvalido(context.Context, *GLance) (*GStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method PublicaLanceInvalido not implemented")
}
func (UnimplementedGatewayServiceServer) PublicaLanceValido(context.Context, *GLance) (*GStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method PublicaLanceValido not implemented")
}
func (UnimplementedGatewayServiceServer) PublicaLeilaoVencedor(context.Context, *GLance) (*GStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method PublicaLeilaoVencedor not implemented")
}
func (UnimplementedGatewayServiceServer) PublicaLinkPagamento(context.Context, *Link) (*GStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method PublicaLinkPagamento not implemented")
}
func (UnimplementedGatewayServiceServer) PublicaStatusPagamento(context.Context, *StatusPayment) (*GStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method PublicaStatusPagamento not implemented")
}
func (UnimplementedGatewayServiceServer) mustEmbedUnimplementedGatewayServiceServer() {}
func (UnimplementedGatewayServiceServer) testEmbeddedByValue()                        {}

// UnsafeGatewayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayServiceServer will
// result in compilation errors.
type UnsafeGatewayServiceServer interface {
	mustEmbedUnimplementedGatewayServiceServer()
}

func RegisterGatewayServiceServer(s grpc.ServiceRegistrar, srv GatewayServiceServer) {
	// If the following call panics, it indicates UnimplementedGatewayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GatewayService_ServiceDesc, srv)
}

func _GatewayService_PublicaLanceInvalido_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GLance)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).PublicaLanceInvalido(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_PublicaLanceInvalido_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).PublicaLanceInvalido(ctx, req.(*GLance))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_PublicaLanceValido_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GLance)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).PublicaLanceValido(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_PublicaLanceValido_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).PublicaLanceValido(ctx, req.(*GLance))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_PublicaLeilaoVencedor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GLance)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).PublicaLeilaoVencedor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_PublicaLeilaoVencedor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).PublicaLeilaoVencedor(ctx, req.(*GLance))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_PublicaLinkPagamento_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Link)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).PublicaLinkPagamento(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_PublicaLinkPagamento_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).PublicaLinkPagamento(ctx, req.(*Link))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_PublicaStatusPagamento_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusPayment)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).PublicaStatusPagamento(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_PublicaStatusPagamento_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).PublicaStatusPagamento(ctx, req.(*StatusPayment))
	}
	return interceptor(ctx, in, info, handler)
}

// GatewayService_ServiceDesc is the grpc.ServiceDesc for GatewayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "GatewayService",
	HandlerType: (*GatewayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PublicaLanceInvalido",
			Handler:    _GatewayService_PublicaLanceInvalido_Handler,
		},
		{
			MethodName: "PublicaLanceValido",
			Handler:    _GatewayService_PublicaLanceValido_Handler,
		},
		{
			MethodName: "PublicaLeilaoVencedor",
			Handler:    _GatewayService_PublicaLeilaoVencedor_Handler,
		},
		{
			MethodName: "PublicaLinkPagamento",
			Handler:    _GatewayService_PublicaLinkPagamento_Handler,
		},
		{
			MethodName: "PublicaStatusPagamento",
			Handler:    _GatewayService_PublicaStatusPagamento_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gateway.proto",
}
