// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.30.2
// source: lance.proto

package proto_models

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LanceService_Create_FullMethodName = "/proto.lance.LanceService/Create"
)

// LanceServiceClient is the client API for LanceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LanceServiceClient interface {
	Create(ctx context.Context, in *Lance, opts ...grpc.CallOption) (*Status, error)
}

type lanceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLanceServiceClient(cc grpc.ClientConnInterface) LanceServiceClient {
	return &lanceServiceClient{cc}
}

func (c *lanceServiceClient) Create(ctx context.Context, in *Lance, opts ...grpc.CallOption) (*Status, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Status)
	err := c.cc.Invoke(ctx, LanceService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LanceServiceServer is the server API for LanceService service.
// All implementations must embed UnimplementedLanceServiceServer
// for forward compatibility.
type LanceServiceServer interface {
	Create(context.Context, *Lance) (*Status, error)
	mustEmbedUnimplementedLanceServiceServer()
}

// UnimplementedLanceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLanceServiceServer struct{}

func (UnimplementedLanceServiceServer) Create(context.Context, *Lance) (*Status, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedLanceServiceServer) mustEmbedUnimplementedLanceServiceServer() {}
func (UnimplementedLanceServiceServer) testEmbeddedByValue()                      {}

// UnsafeLanceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LanceServiceServer will
// result in compilation errors.
type UnsafeLanceServiceServer interface {
	mustEmbedUnimplementedLanceServiceServer()
}

func RegisterLanceServiceServer(s grpc.ServiceRegistrar, srv LanceServiceServer) {
	// If the following call panics, it indicates UnimplementedLanceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LanceService_ServiceDesc, srv)
}

func _LanceService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Lance)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LanceServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LanceService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LanceServiceServer).Create(ctx, req.(*Lance))
	}
	return interceptor(ctx, in, info, handler)
}

// LanceService_ServiceDesc is the grpc.ServiceDesc for LanceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LanceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.lance.LanceService",
	HandlerType: (*LanceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _LanceService_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lance.proto",
}
