// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.30.2
// source: lance.proto

package proto_models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *string                `protobuf:"bytes,1,req,name=status" json:"status,omitempty"`
	Lance         *Lance                 `protobuf:"bytes,2,req,name=lance" json:"lance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_lance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_lance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_lance_proto_rawDescGZIP(), []int{0}
}

func (x *Status) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *Status) GetLance() *Lance {
	if x != nil {
		return x.Lance
	}
	return nil
}

type Lance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeilaoID      *string                `protobuf:"bytes,1,req,name=LeilaoID" json:"LeilaoID,omitempty"`
	UserID        *string                `protobuf:"bytes,2,req,name=UserID" json:"UserID,omitempty"`
	Value         *float32               `protobuf:"fixed32,3,req,name=Value" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lance) Reset() {
	*x = Lance{}
	mi := &file_lance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lance) ProtoMessage() {}

func (x *Lance) ProtoReflect() protoreflect.Message {
	mi := &file_lance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lance.ProtoReflect.Descriptor instead.
func (*Lance) Descriptor() ([]byte, []int) {
	return file_lance_proto_rawDescGZIP(), []int{1}
}

func (x *Lance) GetLeilaoID() string {
	if x != nil && x.LeilaoID != nil {
		return *x.LeilaoID
	}
	return ""
}

func (x *Lance) GetUserID() string {
	if x != nil && x.UserID != nil {
		return *x.UserID
	}
	return ""
}

func (x *Lance) GetValue() float32 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

var File_lance_proto protoreflect.FileDescriptor

const file_lance_proto_rawDesc = "" +
	"\n" +
	"\vlance.proto\x12\vproto.lance\"J\n" +
	"\x06Status\x12\x16\n" +
	"\x06status\x18\x01 \x02(\tR\x06status\x12(\n" +
	"\x05lance\x18\x02 \x02(\v2\x12.proto.lance.LanceR\x05lance\"Q\n" +
	"\x05Lance\x12\x1a\n" +
	"\bLeilaoID\x18\x01 \x02(\tR\bLeilaoID\x12\x16\n" +
	"\x06UserID\x18\x02 \x02(\tR\x06UserID\x12\x14\n" +
	"\x05Value\x18\x03 \x02(\x02R\x05Value2A\n" +
	"\fLanceService\x121\n" +
	"\x06Create\x12\x12.proto.lance.Lance\x1a\x13.proto.lance.StatusB\x0fZ\rproto_models/"

var (
	file_lance_proto_rawDescOnce sync.Once
	file_lance_proto_rawDescData []byte
)

func file_lance_proto_rawDescGZIP() []byte {
	file_lance_proto_rawDescOnce.Do(func() {
		file_lance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lance_proto_rawDesc), len(file_lance_proto_rawDesc)))
	})
	return file_lance_proto_rawDescData
}

var file_lance_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_lance_proto_goTypes = []any{
	(*Status)(nil), // 0: proto.lance.Status
	(*Lance)(nil),  // 1: proto.lance.Lance
}
var file_lance_proto_depIdxs = []int32{
	1, // 0: proto.lance.Status.lance:type_name -> proto.lance.Lance
	1, // 1: proto.lance.LanceService.Create:input_type -> proto.lance.Lance
	0, // 2: proto.lance.LanceService.Create:output_type -> proto.lance.Status
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_lance_proto_init() }
func file_lance_proto_init() {
	if File_lance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lance_proto_rawDesc), len(file_lance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lance_proto_goTypes,
		DependencyIndexes: file_lance_proto_depIdxs,
		MessageInfos:      file_lance_proto_msgTypes,
	}.Build()
	File_lance_proto = out.File
	file_lance_proto_goTypes = nil
	file_lance_proto_depIdxs = nil
}
