// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: leilao.proto

package proto_models

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LeilaoService_Create_FullMethodName = "/LeilaoService/Create"
	LeilaoService_List_FullMethodName   = "/LeilaoService/List"
)

// LeilaoServiceClient is the client API for LeilaoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LeilaoServiceClient interface {
	Create(ctx context.Context, in *LLeilao, opts ...grpc.CallOption) (*LStatus, error)
	List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LLeilao], error)
}

type leilaoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLeilaoServiceClient(cc grpc.ClientConnInterface) LeilaoServiceClient {
	return &leilaoServiceClient{cc}
}

func (c *leilaoServiceClient) Create(ctx context.Context, in *LLeilao, opts ...grpc.CallOption) (*LStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LStatus)
	err := c.cc.Invoke(ctx, LeilaoService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leilaoServiceClient) List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LLeilao], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LeilaoService_ServiceDesc.Streams[0], LeilaoService_List_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, LLeilao]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LeilaoService_ListClient = grpc.ServerStreamingClient[LLeilao]

// LeilaoServiceServer is the server API for LeilaoService service.
// All implementations must embed UnimplementedLeilaoServiceServer
// for forward compatibility.
type LeilaoServiceServer interface {
	Create(context.Context, *LLeilao) (*LStatus, error)
	List(*Empty, grpc.ServerStreamingServer[LLeilao]) error
	mustEmbedUnimplementedLeilaoServiceServer()
}

// UnimplementedLeilaoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLeilaoServiceServer struct{}

func (UnimplementedLeilaoServiceServer) Create(context.Context, *LLeilao) (*LStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedLeilaoServiceServer) List(*Empty, grpc.ServerStreamingServer[LLeilao]) error {
	return status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedLeilaoServiceServer) mustEmbedUnimplementedLeilaoServiceServer() {}
func (UnimplementedLeilaoServiceServer) testEmbeddedByValue()                       {}

// UnsafeLeilaoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LeilaoServiceServer will
// result in compilation errors.
type UnsafeLeilaoServiceServer interface {
	mustEmbedUnimplementedLeilaoServiceServer()
}

func RegisterLeilaoServiceServer(s grpc.ServiceRegistrar, srv LeilaoServiceServer) {
	// If the following call panics, it indicates UnimplementedLeilaoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LeilaoService_ServiceDesc, srv)
}

func _LeilaoService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LLeilao)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeilaoServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeilaoService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeilaoServiceServer).Create(ctx, req.(*LLeilao))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeilaoService_List_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LeilaoServiceServer).List(m, &grpc.GenericServerStream[Empty, LLeilao]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LeilaoService_ListServer = grpc.ServerStreamingServer[LLeilao]

// LeilaoService_ServiceDesc is the grpc.ServiceDesc for LeilaoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LeilaoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "LeilaoService",
	HandlerType: (*LeilaoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _LeilaoService_Create_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "List",
			Handler:       _LeilaoService_List_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "leilao.proto",
}
