// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.30.2
// source: leilao.proto

package proto_models

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LeilaoService_PublicaLeilaoIniciado_FullMethodName   = "/LeilaoService/PublicaLeilaoIniciado"
	LeilaoService_PublicaLeilaoFinalizado_FullMethodName = "/LeilaoService/PublicaLeilaoFinalizado"
)

// LeilaoServiceClient is the client API for LeilaoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LeilaoServiceClient interface {
	PublicaLeilaoIniciado(ctx context.Context, in *Leilao, opts ...grpc.CallOption) (*LStatus, error)
	PublicaLeilaoFinalizado(ctx context.Context, in *Leilao, opts ...grpc.CallOption) (*LStatus, error)
}

type leilaoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLeilaoServiceClient(cc grpc.ClientConnInterface) LeilaoServiceClient {
	return &leilaoServiceClient{cc}
}

func (c *leilaoServiceClient) PublicaLeilaoIniciado(ctx context.Context, in *Leilao, opts ...grpc.CallOption) (*LStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LStatus)
	err := c.cc.Invoke(ctx, LeilaoService_PublicaLeilaoIniciado_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leilaoServiceClient) PublicaLeilaoFinalizado(ctx context.Context, in *Leilao, opts ...grpc.CallOption) (*LStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LStatus)
	err := c.cc.Invoke(ctx, LeilaoService_PublicaLeilaoFinalizado_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LeilaoServiceServer is the server API for LeilaoService service.
// All implementations must embed UnimplementedLeilaoServiceServer
// for forward compatibility.
type LeilaoServiceServer interface {
	PublicaLeilaoIniciado(context.Context, *Leilao) (*LStatus, error)
	PublicaLeilaoFinalizado(context.Context, *Leilao) (*LStatus, error)
	mustEmbedUnimplementedLeilaoServiceServer()
}

// UnimplementedLeilaoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLeilaoServiceServer struct{}

func (UnimplementedLeilaoServiceServer) PublicaLeilaoIniciado(context.Context, *Leilao) (*LStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method PublicaLeilaoIniciado not implemented")
}
func (UnimplementedLeilaoServiceServer) PublicaLeilaoFinalizado(context.Context, *Leilao) (*LStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method PublicaLeilaoFinalizado not implemented")
}
func (UnimplementedLeilaoServiceServer) mustEmbedUnimplementedLeilaoServiceServer() {}
func (UnimplementedLeilaoServiceServer) testEmbeddedByValue()                       {}

// UnsafeLeilaoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LeilaoServiceServer will
// result in compilation errors.
type UnsafeLeilaoServiceServer interface {
	mustEmbedUnimplementedLeilaoServiceServer()
}

func RegisterLeilaoServiceServer(s grpc.ServiceRegistrar, srv LeilaoServiceServer) {
	// If the following call panics, it indicates UnimplementedLeilaoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LeilaoService_ServiceDesc, srv)
}

func _LeilaoService_PublicaLeilaoIniciado_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Leilao)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeilaoServiceServer).PublicaLeilaoIniciado(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeilaoService_PublicaLeilaoIniciado_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeilaoServiceServer).PublicaLeilaoIniciado(ctx, req.(*Leilao))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeilaoService_PublicaLeilaoFinalizado_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Leilao)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeilaoServiceServer).PublicaLeilaoFinalizado(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeilaoService_PublicaLeilaoFinalizado_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeilaoServiceServer).PublicaLeilaoFinalizado(ctx, req.(*Leilao))
	}
	return interceptor(ctx, in, info, handler)
}

// LeilaoService_ServiceDesc is the grpc.ServiceDesc for LeilaoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LeilaoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "LeilaoService",
	HandlerType: (*LeilaoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PublicaLeilaoIniciado",
			Handler:    _LeilaoService_PublicaLeilaoIniciado_Handler,
		},
		{
			MethodName: "PublicaLeilaoFinalizado",
			Handler:    _LeilaoService_PublicaLeilaoFinalizado_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "leilao.proto",
}
