// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.30.2
// source: pagamento.proto

package proto_models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *string                `protobuf:"bytes,1,req,name=status" json:"status,omitempty"`
	Lance         *LanceVencedor         `protobuf:"bytes,2,req,name=lance" json:"lance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PStatus) Reset() {
	*x = PStatus{}
	mi := &file_pagamento_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PStatus) ProtoMessage() {}

func (x *PStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pagamento_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PStatus.ProtoReflect.Descriptor instead.
func (*PStatus) Descriptor() ([]byte, []int) {
	return file_pagamento_proto_rawDescGZIP(), []int{0}
}

func (x *PStatus) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *PStatus) GetLance() *LanceVencedor {
	if x != nil {
		return x.Lance
	}
	return nil
}

type LanceVencedor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeilaoID      *string                `protobuf:"bytes,1,req,name=LeilaoID" json:"LeilaoID,omitempty"`
	UserID        *string                `protobuf:"bytes,2,req,name=UserID" json:"UserID,omitempty"`
	Value         *float32               `protobuf:"fixed32,3,req,name=Value" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LanceVencedor) Reset() {
	*x = LanceVencedor{}
	mi := &file_pagamento_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LanceVencedor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LanceVencedor) ProtoMessage() {}

func (x *LanceVencedor) ProtoReflect() protoreflect.Message {
	mi := &file_pagamento_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LanceVencedor.ProtoReflect.Descriptor instead.
func (*LanceVencedor) Descriptor() ([]byte, []int) {
	return file_pagamento_proto_rawDescGZIP(), []int{1}
}

func (x *LanceVencedor) GetLeilaoID() string {
	if x != nil && x.LeilaoID != nil {
		return *x.LeilaoID
	}
	return ""
}

func (x *LanceVencedor) GetUserID() string {
	if x != nil && x.UserID != nil {
		return *x.UserID
	}
	return ""
}

func (x *LanceVencedor) GetValue() float32 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

var File_pagamento_proto protoreflect.FileDescriptor

const file_pagamento_proto_rawDesc = "" +
	"\n" +
	"\x0fpagamento.proto\"G\n" +
	"\aPStatus\x12\x16\n" +
	"\x06status\x18\x01 \x02(\tR\x06status\x12$\n" +
	"\x05lance\x18\x02 \x02(\v2\x0e.LanceVencedorR\x05lance\"Y\n" +
	"\rLanceVencedor\x12\x1a\n" +
	"\bLeilaoID\x18\x01 \x02(\tR\bLeilaoID\x12\x16\n" +
	"\x06UserID\x18\x02 \x02(\tR\x06UserID\x12\x14\n" +
	"\x05Value\x18\x03 \x02(\x02R\x05Value2D\n" +
	"\x10PagamentoService\x120\n" +
	"\x14PublicaLanceVencedor\x12\x0e.LanceVencedor\x1a\b.PStatusB\x0fZ\rproto_models/"

var (
	file_pagamento_proto_rawDescOnce sync.Once
	file_pagamento_proto_rawDescData []byte
)

func file_pagamento_proto_rawDescGZIP() []byte {
	file_pagamento_proto_rawDescOnce.Do(func() {
		file_pagamento_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pagamento_proto_rawDesc), len(file_pagamento_proto_rawDesc)))
	})
	return file_pagamento_proto_rawDescData
}

var file_pagamento_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pagamento_proto_goTypes = []any{
	(*PStatus)(nil),       // 0: PStatus
	(*LanceVencedor)(nil), // 1: LanceVencedor
}
var file_pagamento_proto_depIdxs = []int32{
	1, // 0: PStatus.lance:type_name -> LanceVencedor
	1, // 1: PagamentoService.PublicaLanceVencedor:input_type -> LanceVencedor
	0, // 2: PagamentoService.PublicaLanceVencedor:output_type -> PStatus
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pagamento_proto_init() }
func file_pagamento_proto_init() {
	if File_pagamento_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pagamento_proto_rawDesc), len(file_pagamento_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pagamento_proto_goTypes,
		DependencyIndexes: file_pagamento_proto_depIdxs,
		MessageInfos:      file_pagamento_proto_msgTypes,
	}.Build()
	File_pagamento_proto = out.File
	file_pagamento_proto_goTypes = nil
	file_pagamento_proto_depIdxs = nil
}
